# Generated by Django 5.2.1 on 2025-06-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Ваш коментар"),
        ),
    ]
