# Generated by Django 5.2.1 on 2025-06-16 10:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
        ),
    ]
