# Generated by Django 5.2.1 on 2025-06-16 11:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
