# Generated by Django 5.2.1 on 2025-06-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_product_price_product_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
