# Generated by Django 5.2.1 on 2025-06-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogPost",
        ),
    ]
