# Generated by Django 5.2.1 on 2025-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="products/videos/"),
        ),
    ]
