# Generated by Django 5.2.1 on 2025-06-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
