# Generated by Django 5.2.1 on 2025-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_product_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True,
                default="_______________",
                max_length=100,
                verbose_name="Серійний номер",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Гарантія (міс.)"
            ),
        ),
    ]
