# Generated by Django 5.2.1 on 2026-02-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_product_serial_number_product_warranty_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube посилання"),
        ),
        migrations.AlterField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True, default="->", max_length=100, verbose_name="Серійний номер"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveIntegerField(
                default=24, verbose_name="Гарантія (24 міс.)"
            ),
        ),
    ]
