# Generated by Django 5.2.1 on 2026-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_product_youtube_url_alter_product_serial_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="warranty_months",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Гарантія (12 міс.)"
            ),
        ),
    ]
