# Generated by Django 5.2.1 on 2026-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_product_warranty_months"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="serial_number",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Серійний номер"
            ),
        ),
    ]
